### ISSUE TITLE
edit maintop.exe

### ISSUE THREAD

**Issue by derekzyl** [portalmod/mod-app#15]
i wanna add some features like pass-wording the data collected to the software i hope to get positive responses

**Comment by odurc** [comment]
Hi @derekzyl. Can you elaborate a bit more your idea?

**Comment by derekzyl** [comment]
okay there is this printer software that i got in my firm(a printing press) the software is called MAINTOP it majorly gets the data to be printed from the system before the data is sent to the printer for printing. and my boss wants the app edited so he could be the only one that can delete the data that comes into the software so he can keep records of job done anytime he wishes. currently anyone can delete data from the software and it seems to not be good for business

**Comment by odurc** [comment]
I pretty sure you're in the wrong place ;)
This repository is from https://moddevices.com an audio devices company.

**Comment by derekzyl** [comment]
thank you very much
