### ISSUE TITLE
Error: make: *** No rule to make target 'source/ui_mod_pedalboard_open.py', needed by 'UI'.  Stop.

### ISSUE THREAD

**Issue by buscon** [portalmod/mod-app#19]
Hi,

I am running linux Mint and I wanted to try out the mod-app.
I installed the dependencies and the submodules (mod-ui and mod-host), but when I run make I get:
make: *** No rule to make target 'source/ui_mod_pedalboard_open.py', needed by 'UI'.  Stop.

what is the problem?

Thanks.

**Comment by falkTX** [comment]
Not sure, but this repo is deprecated, things no longer work correctly with newer tornado and python3.10+
Best to use https://github.com/moddevices/mod-panel instead

**Comment by buscon** [comment]
thanks, mod-panel is what I need :)
