### ISSUE TITLE
Compile mod-app problem

### ISSUE THREAD

**Issue by dkmorb** [portalmod/mod-app#9]
Hi, i'm new here.
I'm trying to compile and launch mod-app from console by command:
python source/mod-app

but I obtain:
Traceback (most recent call last):
  File "source/mod-app", line 22, in <module>
    from mod_host import *
  File "c:\gnu\source\mod-app\source\mod_host.py", line 22, in <module>
    from mod_settings import *
  File "c:\gnu\source\mod-app\source\mod_settings.py", line 34, in <module>
    from ui_mod_settings import Ui_SettingsWindow
ImportError: No module named 'ui_mod_settings'

Where can I find this module? I assume I need to install other package...
P.S.: Doh! I'm using last and upgraded KXStudio (your prebuild binary works correctly)

**Comment by dkmorb** [comment]
Sorry, 
probably I need to compile and run mod-host package, but i don't know the right way...

**Comment by falkTX** [comment]
You just have to do:

```
make
```

Then you should be able to run mod-app.

I've updated the README with this information.

**Comment by dkmorb** [comment]
Ok, thanks! 
I need to reinstall also: 
sudo apt-get install python3-pymongo-ext python3-pymongo python3-bson python3-urllib3 
because 
apt-get autoremove 
remove these dependencies :-)

**Comment by falkTX** [comment]
Those are dependencies of mod-ui, not mod-app.
But yeah, pymongo and bson are missing from mod-ui dependencies list.
urllib3 is no longer needed.

**Comment by dkmorb** [comment]
Sorry, I'll whip myself...
uh, last thing: TAP DeEsser and BigMuff Pi have some GUI problems.
Bye.
![image](https://cloud.githubusercontent.com/assets/8875052/7463737/4b528b5a-f2bc-11e4-974a-703e27a7705f.png)

**Comment by falkTX** [comment]
Known issues, to be solved later.
If those bother you too much please report them separately (new bug report).

**Comment by dkmorb** [comment]
No, this doesn't bother me. Probably I'll try to take a look, just for funny.
Bye!
